services:
  db:
    image: mysql:8.1.0-oracle
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=cicd
      - MYSQL_PASSWORD=qqqq1111
      - MYSQL_DATABASE=cicd
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: /healthchecks/mysql-healthcheck
      interval: "5s"
    ports:
      - "3306:3306"

volumes:
  db:
